### ISSUE TITLE
Cloud Providers

### ISSUE THREAD

**Issue by berniedurfee** [Lambda-School-Labs/labs-engineering-standards#13]
Pick one or more:

- [ ] AWS
- [ ] Azure
- [ ] GCE
- [ ] Heroku
- [ ] Zeit
- [ ] Other

**Comment by berniedurfee** [comment]
AWS is in for sure...
I think we should continue to support Heroku...
GCE and Azure are not being used, at least as far as I can tell and I think we should prohibit them to narrow what we need to support...
Zeit and Netlify are popular and lightweight, I think we should continue to support them, thoughts?

**Comment by tinomen** [comment]
I'd be fine if heroku was all they got at the moment. 

AWS opens a world of possibilities but I'm honestly questioning my ability to support these teams with a broader set of tools. Eg. lambda functions are cool but worthless (or a pain) unless you setup an api gateway. If this is now easy and I'm just out of date then ignore this. Otherwise AWS is a deep sea of config that we'd need some automation around.

**Comment by berniedurfee** [comment]
AWS has a bunch of high-level services that replicate much of the rapid development lifecycle provided by Heroku, etc.

Amplify and Beanstalk are pretty easy to plug and play. Plus with all the other services available to augment these more simplified services.

**Comment by tinomen** [comment]
I propose we close the issue with the hosts that were merged in and published.
