### ISSUE TITLE
Add Next.js to allowed React frameworks

### ISSUE THREAD

**Issue by tinomen** [Lambda-School-Labs/labs-engineering-standards#43]
This is related to issue #12 since we don't have anything for the web front end frameworks yet.

- React
- Next.js - I get requests for this one in Labs and X. I looked at in PT5 and it is very react like.

should we make styling libs/systems a separate issue?

**Comment by berniedurfee** [comment]
Good timing! I just submitted a PR to specifically callout Vue and Angular: #44 

I added Create React App as allowed and Next.js as prohibited.

Also, I just added some verbiage to the frontpage to stress that if it's not allowed in the standards, it's probably not allowed: https://lambda-school-labs.github.io/labs-engineering-standards/#standards

**Comment by benjamin-t-wilson** [comment]
How does this affect groups who have already had their PVD approved with Next.js in their stack?

**Comment by LeTanque** [comment]
First, I really like having guidelines around labs engineering standards!

**With regards to Next.js in Labs:**

Not to be overly technical, but CRA is React AND Next.js is React. The differences are, more or less, webpack configuration, how the developer thinks about their app when developing, and the `react-scripts` dependency. But at its core Next.js is React.

I completely agree with the reasoning on the PR that we are a "react shop". By that reasoning, there is little reason to prohibit Next.js in labs.

**Hypotheticals:**
In the event that a team learns how to configure webpack to SSR versus starting their application with Next.js, are we going to stop them?

In the event that a team would like to eject their CRA (allowing for any customization), does that prevent them from passing Labs?

**Why I think it matters:**
Part of Labs is Technical Research and teams currently research things (for the frontend) like React, Angular, and Vue. Most teams choose because they know it already and there is not enough time to learn a whole new framework. But the process exists to help simulate something that happens in the real world all the time: research. Research is good!

In this research, Next.js is a viable solution (one that many teams evaluate). It's not a whole new framework (like Vue or Angular) and developers already know most of what they need to know to get started.

**The upsides of allowing for Next.js:**
Resume booster!

Healthy research exercise (whether they choose it or not).

We teach how to learn, why stop now?

Another way for developers to differentiate themselves from others.

**Final Thoughts:**
I really think Next.js should be an available option for teams! If not for all, at least on a case by case business. Maybe only if a team can research and come up with a convincing reason why they feel Next.js would help their users and/or the effectiveness of their project. 

For my Labs team, I led the research on Next.js and we ended up _not_ using it for Labs. But the process of researching and thinking critically about how our problem related to our solutions helped me understand what we were building at a deeper level. That research, in my opinion, helped our team finish as one of the strongest apps in our cohort.

**Comment by berniedurfee** [comment]
> How does this affect groups who have already had their PVD approved with Next.js in their stack?

It will not. There's a note on the Product Engineering page in the handbook that says that these changes are not intended to be disruptive. Projects already in-flight will continue as designed and we'll carefully plan changes to bring all projects into compliance.

**Comment by berniedurfee** [comment]
Comments below...

> _First, I really like having guidelines around labs engineering standards!_
> Thank you very much for detailing this stuff in a living document. I think that's really smart and I'm super grateful to be able to contribute to the discussion!

Thanks!

> Not to be overly technical, but CRA is React AND Next.js is React. The differences are, more or less, webpack configuration, how the developer thinks about their app when developing, and the `react-scripts` dependency. But at its core Next.js is React.

Yep, that section is for 'frameworks'. We could probably break it down, but I would consider React a framework and I also consider CRA and Next.js to be frameworks as well. We probably need to develop a more accurate taxonomy, but trying to keep things in big buckets for now.


> I completely agree with the reasoning on the PR that we are a "react shop". By that reasoning, there is little reason to prohibit Next.js in labs.

The motivation behind the standards that prohibit specific languages or frameworks is to reduce the variability of project architecture and implementation in Labs. We'll have dozens of projects in-flight and hundreds of projects in our library. Trying to reduce the variability is critical for us to be able to support dozens of teams with a handful of architects and leads.

Having teams using both Next.js _and_ CRA for their projects doubles the technologies that we need to support over the long term. Given that neither is (arguably) significantly better than the other, choosing one over the other has the benefit of allowing us to concentrate our expertise and support on one vs both.

> **Hypotheticals:**
> In the event that a team learns how to configure webpack to SSR versus starting their application with Next.js, are we going to stop them?

We may... but it depends. These standards will grow and change as needed. If a team ends up doing SSR while still being compliant and it ends up not being an issue, it's fine. If teams start doing SSR and it ends up creating issues with providing adequate support for teams, we may add a standard that prohibits SSR. The goal is to create the right balance of guardrails and open spaces to enable creativity without stifling productivity and vice versa. Not easy!

> In the event that a team would like to eject their CRA (allowing for any customization), does that prevent them from passing Labs?

Technically this doesn't violate the standards, so no.

> **Why I think it matters:**
> Part of Labs is Technical Research and teams currently research things (for the frontend) like React, Angular, and Vue. Most teams choose because they know it already and there is not enough time to learn a whole new framework. But the process exists to help simulate something that happens in the real world all the time: research. Research is good!

Yes! But per my discussion above. 
> 
> In this research, Next.js is a viable solution (one that many teams evaluate). It's not a whole new framework (like Vue or Angular) and developers already know most of what they need to know to get started.
> 
> **The upsides of allowing for Next.js:**
> Resume booster!
> 
> Healthy research exercise (whether they choose it or not).
> 
> We teach how to learn, why stop now?
> 
> Another way for developers to differentiate themselves from others.
> 
> **Final Thoughts:**
> I really think Next.js should be an available option for teams! If not for all, at least on a case by case business. Maybe only if a team can research and come up with a convincing reason why they feel Next.js would help their users and/or the effectiveness of their project.
> 
> For my Labs team, I led the research on Next.js and we ended up _not_ using it for Labs. But the process of researching and thinking critically about how our problem related to our solutions helped me understand what we were building at a deeper level. That research, in my opinion, helped our team finish as one of the strongest apps in our cohort.

**Comment by berniedurfee** [comment]
Comments below...

> _First, I really like having guidelines around labs engineering standards!_
> Thank you very much for detailing this stuff in a living document. I think that's really smart and I'm super grateful to be able to contribute to the discussion!

Thanks!

> Not to be overly technical, but CRA is React AND Next.js is React. The differences are, more or less, webpack configuration, how the developer thinks about their app when developing, and the `react-scripts` dependency. But at its core Next.js is React.

Yep, that section is for 'frameworks'. We could probably break it down, but I would consider React a framework and I also consider CRA and Next.js to be frameworks as well. We probably need to develop a more accurate taxonomy, but trying to keep things in big buckets for now.


> I completely agree with the reasoning on the PR that we are a "react shop". By that reasoning, there is little reason to prohibit Next.js in labs.

The motivation behind the standards that prohibit specific languages or frameworks is to reduce the variability of project architecture and implementation in Labs. We'll have dozens of projects in-flight and hundreds of projects in our library. Trying to reduce the variability is critical for us to be able to support dozens of teams with a handful of architects and leads.

Having teams using both Next.js _and_ CRA for their projects doubles the technologies that we need to support over the long term. Given that neither is (arguably) significantly better than the other, choosing one over the other has the benefit of allowing us to concentrate our expertise and support on one vs both.

> **Hypotheticals:**
> In the event that a team learns how to configure webpack to SSR versus starting their application with Next.js, are we going to stop them?

We may... but it depends. These standards will grow and change as needed. If a team ends up doing SSR while still being compliant and it ends up not being an issue, it's fine. If teams start doing SSR and it ends up creating issues with providing adequate support for teams, we may add a standard that prohibits SSR. The goal is to create the right balance of guardrails and open spaces to enable creativity without stifling productivity and vice versa. Not easy!

> In the event that a team would like to eject their CRA (allowing for any customization), does that prevent them from passing Labs?

Technically this doesn't violate the standards, so no.

> **Why I think it matters:**
> Part of Labs is Technical Research and teams currently research things (for the frontend) like React, Angular, and Vue. Most teams choose because they know it already and there is not enough time to learn a whole new framework. But the process exists to help simulate something that happens in the real world all the time: research. Research is good!

Yes! But per my discussion above, the lifecycle of the applications being built is _much_ longer than the time a particular team will be working on them. That's goes to the heart of the need to narrow the variability from project to project. With less variability, we can focus our training and support to create far more depth than if we supported a large number (or unlimited number) of choices. It's a tradeoff, but it's necessary for longevity and quality.

> In this research, Next.js is a viable solution (one that many teams evaluate). It's not a whole new framework (like Vue or Angular) and developers already know most of what they need to know to get started.

This may be something that is reconsidered in the near future, but for now, we're going to start with a narrow selection and broaden the scope over time with careful and deliberate decisions.

> **The upsides of allowing for Next.js:**
> Resume booster!
> Healthy research exercise (whether they choose it or not).
> We teach how to learn, why stop now?
> Another way for developers to differentiate themselves from others.

100% agree! However, every option added to the standards has a real cost associated with it. There are also real risks to an organization supporting too many options. The value of each option needs to be weighed against the cost and risk of supporting it. It's that tradeoff that takes some time to work through.

> **Final Thoughts:**
> I really think Next.js should be an available option for teams! If not for all, at least on a case by case business. Maybe only if a team can research and come up with a convincing reason why they feel Next.js would help their users and/or the effectiveness of their project.
> 
> For my Labs team, I led the research on Next.js and we ended up _not_ using it for Labs. But the process of researching and thinking critically about how our problem related to our solutions helped me understand what we were building at a deeper level. That research, in my opinion, helped our team finish as one of the strongest apps in our cohort.

First, thank you _very_ much for your candid and thoughtful feedback. This is exactly the kind of conversation that I was hoping would come out of this process.

I'll give you my thoughts on the situation. In my experience, the ideal state for an individual developer or team is to have many options, the ideal state for those that need to manage many projects and teams is to have very few options. The right solution is somewhere in between. A set of options that allows developers to be creative and optimize for specific scenarios, while still allowing an organization to maintain a manageable level required knowledge and tech debt.

As for the technical research, we're looking for _far_ more depth than just choosing Next.js or CRA. In 99% of cases, a coin flip would suffice. But technical research should be more about architecture, data modeling, API structure, testing strategy, scaling requirement, security posture, etc.

In any event, the Engineering Manager team discusses and decides on each incoming issue. We'll discuss this soon and will be back with a decision... at least for this moment in time.

Thanks again!

**Comment by berniedurfee** [comment]
Let's make a decision as whether to add Next.js or stick with CRA only for now.

**Comment by adventurini** [comment]
There is almost nothing to gain for students using NextJS. It comes with a lot of bugs, workarounds, and frustration. The learning curve might seem small at first, but it is not. The upside is practically 0 for using NextJS (an arguable performance uptick at scale, while none on a dry crud app). While the downside is a crummy project because a team was trying to use tech that they did not know or need.

The tech stack should be chosen by Lambda so it can be supported by TLs and staff. Teams that go rogue are susceptible to blockers that remain in the abyss.

I TL'd for an extremely powerful team for Labs and we were not able to deploy with Next. You don't want to open up a can of worms for teams that will waste two weeks banging their heads because they had no idea what they were getting into.

**Comment by berniedurfee** [comment]
> There is almost nothing to gain for students using NextJS. It comes with a lot of bugs, workarounds, and frustration. The learning curve might seem small at first, but it is not. The upside is practically 0 for using NextJS (an arguable performance uptick at scale, while none on a dry crud app). While the downside is a crummy project because a team was trying to use tech that they did not know or need.

Except that I know lots of really talented developers that would completely disagree. :) The reality is, programming languages, frameworks and tools are all really good at some stuff for some people in some scenario... or they would never exist.

There's a human element that makes us battle over Pepsi or Coke, Ford or Chevy, Makita or Bosch... even though the differences are objectively and empirically negligible. We're all '[maximizers](https://en.wikipedia.org/wiki/Maximization_(psychology))' to some extent.

I've come to find that the best way to make good decisions around languages, frameworks and tools is to not spend too much time on it unless you know _exactly_ what you're optimizing for and most times you rarely need to put much time into the decision because you can do great things with any number of available languages, frameworks and tools.

> The tech stack should be chosen by Lambda so it can be supported by TLs and staff. Teams that go rogue are susceptible to blockers that remain in the abyss.

I agree with the first sentiment, not so much with the second. What we're optimizing for with these standards is mainly that we have enough depth of knowledge in our staff to deeply educate teams on a specific set of technologies that are representative of the current state of the practice of software engineering. That means a minimal set of modern mainstream technologies.

Teams that make a case for going off the ranch and exploring new tech are actually encouraged. With the caveat that there may not be someone on staff to help push through issues. I hope we always have a few teams that find, for their particular product, that they need to optimize for something that requires something outside the lines of the standards. They'll be pushing the boundaries to ensure that we don't get complacent.

> I TL'd for an extremely powerful team for Labs and we were not able to deploy with Next. You don't want to open up a can of worms for teams that will waste two weeks banging their heads because they had no idea what they were getting into.
> 
> Using a cool, new tech stack has not proven to get anyone hired. A good Labs project however has done so, many times. Nothing should risk the outcome of the final product.

This I agree with, but I'm also glad that the team tried something new and learned from it. That learning is more valuable in the context of Labs than if the time had been spent building product. There's an old saying around here that goes something like: "In Labs, producing awesome products is a side-effect of producing awesome people... not the other way 'round."

Thank you @adventurini for the input, much appreciated! 👍

**Comment by adventurini** [comment]
> Except that I know lots of really talented developers that would completely disagree. :) The reality is, programming languages, frameworks and tools are all really good at some stuff for some people in some scenario... or they would never exist.

Obviously there is upside, drawbacks, risk/ benefits to using any tool, language, or framework. But this is a scenario of using ReactJS vs. NextJs in a Labs project. The upside is conversational for an interview, which has extremely limited upside, if any at all. So I am not sure why a talented developer's opinion would matter, being that the argument is not NextJS vs. ReactJs in a scaling application. The argument is having student developers use React, which they know, or NextJS, which they do not, in an 8 week curriculum. Upside is "I used Next," downside is an awful Labs project and frustrated team.

I would argue that spending time learning a new tech stack takes away from the CRUD operations and design that gets people hired. I have seen a lot of people get hired off of their Labs projects and the tech stack is never what did it. I have been through three Labs and there are still a lot of bad Labs projects that are running out there. Until that ends, I think the tech stack should be a given.

Side note: I only use Next and will only ever use Next from now on. It is awesome for performance and the future is very bright for the framework. If everyone wants to use it in Labs, then maybe change the Lambda curriculum to add SSR.

**Comment by LeTanque** [comment]
From Anthony:
> There is almost nothing to gain for students using NextJS. It comes with a lot of bugs, workarounds, and frustration. 

It's true that one must adjust their approach to building applications with Next.js. This idea was one of my main reasons for voting against it during Labs. 

What students can gain from exploring Next.js is knowledge. What they gain, potentially, is a deeper understanding of Next.js, CRA, or both. All they have known and used in the curriculum up to Labs has been CRA. Giving students space to explore options is healthy, even if they don't choose anything new.


From Bernie:
> Teams that make a case for going off the ranch and exploring new tech are actually encouraged. With the caveat that there may not be someone on staff to help push through issues. 

I agree with a conditional remove-this-sticker-at-your-own-risk approach. 

At the end of the day, I think most teams will probably not end up working with Next.js during Labs. I just think outright prohibition is a little too absolute. I can imagine a scenario where Next.js becomes as popular as React and that a hardline stance again Next.js will be disadvantageous. 


From Anthony:
> Side note: I only use Next and will only ever use Next from now on. 

Haha, well... if there's one constant in front end development, it's that everything changes and it changes pretty frequently. Next.js is well maintained with a strong community, it's SSR which is all the rage right now. But if and when that changes, so will everything around it. Just think, how many developers said the same thing about jQuery 5 years ago? 

I wouldn't be surprised if we are building monolithic lower-level web interfaces 5 years from now, with a framework that resembles django more than it resembles CRA or Next.js.

**Comment by berniedurfee** [comment]
Discussed and ratified February 13th, 2020
