### ISSUE TITLE
Authentication Providers

### ISSUE THREAD

**Issue by ryan-hamblin** [Lambda-School-Labs/labs-engineering-standards#61]
We've had quite a few teams looking into different OAuth and Auth providers that are out there for use. I know for internal projects that consume User Data we're using Okta as a provided solution. However, for other products that don't require student data I'd like to consider a list of Auth Providers and standardize. I'm not married to anyone one single solution and of course, if teams need the use of Oauth for things like Facebook's Graph Data or Google info we should encourage those providers. 

Here is the list that they have come up with so far: 
- Firebase
- Auth0
- AWS Cognito??? Was looking around at what AWS provides here. Not sure if this it or if there are other options. 
- Rolling their own Authentication flow w/ JWTs

**Comment by ShandaWoods** [comment]
Through initial research on our project, I think Firebase (for reporting/analytics/ease of integration with OAuth in previous code base) should be considered and standardized.

**Comment by derekjpeters** [comment]
Yes we need another one outside of Okta.  It would be good to have another solution for students to choose from.  Firebase, while not my favorite does have a good auth system.  Auth0 is another good one but I am not sure of the cost.  Just some of the topics that we are going through in PT8 and Okta may not be the best solution.

**Comment by mrzacsmith** [comment]
Our team agrees with the comments here, though Okta has it uses as stated by Ryan, it is not a total solution. Firebase integration is a norm for the industry and would provide practical use experience for our teams. Additionally, as stated by Ryan that the current wording does not allow for project driven authentication flow with JWTs. It is requested that at a minimum, that Firebase Authentication and team driver JWT authentication be standardized. This is currently an unknown that is causing project uncertainty.

**Comment by berniedurfee** [comment]
Ideally, our standards will support the minimum number of technology options for component in a typical tech stack. Constraining options will allow us (Lambda School) to provide deep and robust support and training on those tools. Cross-training several people on a single product is far more practical than on many different products.

Gartner recently named Okta the market leader in access management platforms: https://www.okta.com/resources/access-management-leader-gartner-magic-quadrant/

This is a pretty good indicator that Okta is well represented in the market and has a robust enough set of features and capabilities to support all or nearly all of the products created in Labs.

I like having options as well, but we need to be pragmatic as every additional platform we support incurs a real cost: training, documenting, supporting, maintaining, risk, etc.

This makes it imperative that we carefully consider adding any additional options to our standards.

@ryan-hamblin @ShandaWoods @derekjpeters @mrzacsmith 

Some questions to gauge the necessity of adding more providers:

What specific features does Okta lack that other providers like Firebase, Auth0, etc. do support?

Are those features absolutely critical to a particular Labs project? What makes that project unique?

Are we using any other authentication/authorization standards outside of OAuth?

**Comment by mrzacsmith** [comment]
@berniedurfee In response to your questions:
I appreciate your time and consideration of clarifying and standardizing new or currently taught skills.  

1. Can you clarify the use of the instructed method of authentication using JWT. Based on the Engineering docs and @ryan-hamblin reply, if appears as if we are not allowed to build out own authentication and must use okta. 

2. We receive zero training or even exposure to okta during our Full Stack courses, if this is the only alternative, can you address this with curriculum and have them add it to the lessons. Even if just a 10 min, this is okta and a quick run down of how it works with React / NodeJs. 

3. Your questions: 
_What specific features does Okta lack that other providers like Firebase, Auth0, etc. do support?_
No features that I currently see, rather it is exposure to and training available. Firebase and Auth0 are options in build week etc. 
_Are those features absolutely critical to a particular Labs project? What makes that project unique?_ Not that I am aware.
_Are we using any other authentication/authorization standards outside of OAuth?_
JWT are used and taught throughout the Full Stack curriculum, in addition to sessions and cookies.

**Comment by tinomen** [comment]
Don't forget that for OAuth client purposes a team can easily use the approved passport.js to solve those basic needs. This method has only a few more steps required over an Okta or Auth0. 

http://www.passportjs.org/

**Comment by berniedurfee** [comment]
@mrzacsmith 

> 1. Can you clarify the use of the instructed method of authentication using JWT. Based on the Engineering docs and @ryan-hamblin reply, if appears as if we are not allowed to build out own authentication and must use okta.

JWT is part of the OpenID Connect standard, so JWTs are definitely still part of the authentication flow. Yes, we do _not_ want student products to house and protect credentials. Many (if not most) companies want to outsource identity management to industry leading providers like Okta because it is not part of their core business and the overhead is considerable.

> 2. We receive zero training or even exposure to okta during our Full Stack courses, if this is the only alternative, can you address this with curriculum and have them add it to the lessons. Even if just a 10 min, this is okta and a quick run down of how it works with React / NodeJs.

The Labs program is often not in lock-step with the learning side of Lambda School. This is actually, to a certain extent, by design. As the intent of Labs is to be a realistic simulation of working in the software industry, we want to challenge students with opportunities to quickly learn and apply new technologies. The odds that you'll end up using all of (or even most of) the specific technologies you learn in Lambda School in your job are small. More than likely is that you'll need to very quickly learn a new language, tool, platform or pattern within the first couple weeks. We want students to experience this 'learning on the fly' in Labs to get comfortable with the continuous learning skill that's required especially in this industry.

> 3. Your questions:
>    _What specific features does Okta lack that other providers like Firebase, Auth0, etc. do support?_
>    No features that I currently see, rather it is exposure to and training available. Firebase and Auth0 are options in build week etc.

Okta will likely be introduced in build weeks in the near future. The intent of the Labs Engineering Standards are that they will be extended to build weeks as well.

>    _Are those features absolutely critical to a particular Labs project? What makes that project unique?_ Not that I am aware.

This is where I need to replace my engineering hat with my manager hat. As an engineer, I love learning and using new technologies. It actually pains me somewhat to narrow the scope of options, because as an engineer I love options! But as an engineering _manager_ I need to balance that with the ever present constraints on available resources. Teams and organizations are _always_ limited in available resources (people, time, budget, etc.) so I need to push for limited options because it allow us to apply those limited resources more efficiently.

Thus without a _very_ specific and well articulated need for another option, I can't agree to adding more options if only for the sake of having more options.

>    _Are we using any other authentication/authorization standards outside of OAuth?_
>    JWT are used and taught throughout the Full Stack curriculum, in addition to sessions and cookies.

JWT is part of the OAuth standard, of which OIDC is based. Using Okta (or any OAuth 2.0 compliant identity management platform) will include the use of JWT as per the spec: https://tools.ietf.org/html/rfc7519

What you learned about JWT, cookies and sessions is still all very much applicable. You just won't have a 'password' field in your database to deal with or a login page on your frontend, your identity provider will provide those for you. Your application _relies_ on the identity provider for that service, which is very much inline with how many companies handle identity.

Having said all this above though... we'll still be discussing this at our next engineering meeting to make a decision. Thank you all for the input! :)

**Comment by mrzacsmith** [comment]
@berniedurfee I do respect your time and thoughts on this matter, and though I agree with much of what you said I do have a couple further comments on this issue. The first, 

> The Labs program is often not in lock-step with the learning side of Lambda School. This is actually, to a certain extent, by design. As the intent of Labs is to be a realistic simulation of working in the software industry, we want to challenge students with opportunities to quickly learn and apply new technologies. The odds that you'll end up using all of (or even most of) the specific technologies you learn in Lambda School in your job are small. More than likely is that you'll need to very quickly learn a new language, tool, platform or pattern within the first couple weeks. We want students to experience this 'learning on the fly' in Labs to get comfortable with the continuous learning skill that's required especially in this industry.

I completely agree! I have been in and around the industry for a long time and do not challenge you in any capacity on the above statement. I support it, and this is part of my shock when we were so restricted in the Labs Engineering document concerning technologies like GraphQL (amended and added after we changed our architecture) and MongoDB. That said, I understand the decision, though wonder if some areas of the engineering document don't deserve a revisit using your statement above. 

> Your questions: What specific features does Okta lack that other providers like Firebase, Auth0, etc. do support? No features that I currently see, rather it is exposure to and training available. Firebase and Auth0 are options in build week etc. (Quoting me)

After fighting with the React setup for authentication using Okta, I must say that there is, in my opinion a significant difference in the availability and current relevant materials for Firebase over Okta. Much of the Okta documentation is a bit outdated, leading to errors that are due to Okta not updating their documentation. This is par for the course, I am aware though the advertised, add authentication in minutes is a weee (a lot) exaggerated. Not that this response is meant to change opinions, rather to provide an answer that is slightly more educated than my previous one. Having had no experience with Okta until really the last 9 hours ... I was unable to provide any differences. Though a small issue, quality and availability of current and relevant documentation has its benefits.  

Once again, thanks for your time and clarification to this discussion and the eventual addition to the labs engineering document. 

FYI ... password fields, and the many other parts that go along with that will not be missed!

**Comment by berniedurfee** [comment]
We're going to stick with Okta as our sole means of identity management at the current time. This provides a robust and full-featured platform for managing identities.
