### ISSUE TITLE
Should github repo names include the cohort name or number?

### ISSUE THREAD

**Issue by tinomen** [Lambda-School-Labs/labs-engineering-standards#63]
For Staff and SLs there isn't a clean way to pull up a list of repos for a cohort. The teams have the cohort name included but the repos are 4 clicks/screens away in github per team. In other sources, such as airtable, there is no equivalent filtering method.

Suggested repo name format
<cohort>-<product>-<purpose>-<postfix>
labs20-mission-control-be
labspt7-homerun-fe

Besides setting a naming standard on the repo what other options exist that will extend beyond github?

**Comment by berniedurfee** [comment]
Mission Control will allow us to easily link cohort, projects and repos. So that's TBD.

I'd strongly suggest we don't use the cohort name in the repo name because it breaks the product vs project paradigm and also makes build-on projects more confusing.

In the interim, I've been playing with using GitHub Topics for labeling a repo with the cohort name that's working on it: https://help.github.com/en/github/administering-a-repository/classifying-your-repository-with-topics

This will allow you to easily filter repos in GitHub by cohort: https://github.com/Lambda-School-Labs?utf8=%E2%9C%93&q=labs20&type=&language=

Once we get Mission Control in place and can link cohort -> project -> repo, we can automatically label repositories. For now, I went through and have been labeling them by hand.

**Comment by tinomen** [comment]
I've been using the topics as well. It does help not having to drill down from teams on github.

Blasted buildons, I didn't think of those. Yeah, this doesn't work for those.
