### ISSUE TITLE
A Proposal To Save GraphQL

### ISSUE THREAD

**Issue by JimmyMcBride** [Lambda-School-Labs/labs-engineering-standards#96]
So on May 7th, a commit was made to master to [exclude GraphQL](https://github.com/Lambda-School-Labs/labs-engineering-standards/commit/890c2e1baab61be30c46c35afbac9d746f54866b) from the list of acceptable technologies. This obviously made me very sad, as I'm a huge fan of GraphQL and would love for anybody who would like to explore this brilliant technology, to be able to make that choice for their team. 

**The Problem**

I think most of the heartache around GraphQL right now is not actually GraphQL, but Prisma. Prisma comes with a lot of baggage. It uses docker which can be a very difficult set up for a lot of Windows users (enabling hyper v, needing Windows 10 Pro). Having 2 servers running, one for Prisma and one for Apollo feels very heavy. It can get frustrating when something works on localhost:7000 and then doesn't work on localhost:8000, and it can get even more frustrating when you change the schema and roll everything back and you have queries for old schema hanging out in you 700/_admin cache that break your attempts to update your actual schema. 

Prisma is an amazing way to put together an amazing and scalable back end that can handle anything. It's a professional tool that is incredibly powerful and useful. However, it has a steeper learning curve than other ways of creating a GraphQL back end with node.js.

**The Solution**

KNEX! :fire: 

If we limit the use of ORM's able to be used for communicating with a Postgres database, then we don't have to ban GraphQL. By adding one single dependency (like apollo-server-express or graphql-yoga) you can turn a vanilla Node.js, knex, express, lambda stack REST API into a full-blown Apollo / GraphQL API.

Just adding one dependency to a lambda curriculum stack is not as scary or intimidating of having to learn AWS, Prisma, Apollo, Docker, GraphQL all at the same time. I think allowing Apollo to remain on the whitelist while making knex the only approved ORM would greatly improve students' experience with GraphQL down the road if they choose that route.

If you're curious what a GraphQL / Knex back end looks like, [check out this GitHub repo](https://github.com/JimmyMcBride/knex-graphql), or [my blog on starting a GraphQL / Knex API from scratch.](https://jimmymcbride.now.sh/blog/knex-graphql)
 
Anyways, just some ramblings from a student that probably doesn't know what he's talking about. I just figured I'd do my best to offer a solution to a problem I'm passionate about. :) :peace_symbol:

**Comment by dswhitely1** [comment]
I think implementing GraphQL is a great learning experience with teams.  Instead of limiting GraphQL, may limit Docker or other technology that can't be implemented like Node Express deployment on Heroku or AWS.

**Comment by raythurman2386** [comment]
I completely agree with this. I absolutely love GraphQL and would hate to see it not be an option for groups in the future. Prisma is getting to be a great option to use with graphql but I do think it is the problem. If groups use KNEX or even TypeORM and TypeGraphQL it is very straight forward and easy to debug. Taking away the ability to utilize GraphQL removes a huge learning experience for the groups. 

If anything ban prismatopia from being utilized for labs since It is so buggy.

**Comment by dave-vazquez** [comment]
This could potentially rescue a lot of build-ons currently using Prisma/GraphQL back-ends. Make them more viable to be picked-up by future teams.

**Comment by gebhartn** [comment]
To add my support for this, I have put together another alternative to using Knex to assist with projects that are currently embedded in the Prisma ecosystem.

[This repository](https://github.com/gebhartn/save-graphql) is built with vanilla JavaScript and Prisma 2 and includes some initialization scripts for schema management and clean up. 

As opposed to Prisma 1, the only requirement for Prisma 2 is that you have a database connection, which is no different than any other ORM, and it can replace Prisma 1 projects with minimal reworking.

**Comment by nickdurbin** [comment]
I want to echo what others have said and ask that you look at keeping GraphQL as an option and removing Prisma till the bugs are worked out. Everyone learns how to use the query builder Knex, but even using an alternative ORM with GraphQL keeps that possibility of using a new technology for Labs. 

Currently, every Lambda student comes out of the curriculum with the same skill set and a very familiar/vanilla set of skills within the JS ecosystem. This allows a student to try and learn a new skill within a team. Something they will more than likely have to do on the job because no one will be using only what Lambda is teaching. 

Does it make it easier to pass off Labs projects? Yes. Is that as beneficial as going into a code base with a new technology that needs to be learned? No.

Keep GraphQL.

**Comment by Memitaru** [comment]
I've lead two project groups using GraphQL. One was using Prismatopia and one was using the method described here. I can confidently say that the main struggle came from the added complexity of Prisma and Docker, not GraphQL in particular.

In fact, the team that used GraphQL with their node/express back end did an amazing job and it was a very valuable and enjoyable experience. 

I think Prismatopia might just be too much new technology to learn in that short of time while still being sure to ship your features, but I think fully removing GraphQL removes the chance for teams to learn an awesome new thing and also makes them miss out on the valuable experience of weighing the pros and cons of GraphQL vs what they've already learned.

**Comment by ryan-hamblin** [comment]
@berniedurfee @tinomen it looks like we have a lot of interest around saving GraphQL here!!

I love the passion. Thank you for all those who've chimed in. We are taking every change we make very seriously and will consider all changes deeply 💯

**Comment by Embiggenerd** [comment]
I don't think being a fan of a spec is a good reason to teach it to bootcamp students. Most of the students are lost in simple stuff like props, state, and writing APIs. Should probably concentrate on advanced SQL, implementing streaming data, async/await, advanced testing, typescript, etc.

That you mention knex tells the story. Students are still relying on knex, they should go to raw sql before you start with more abstractions on top of it.

**Comment by gebhartn** [comment]
> I don't think being a fan of a spec is a good reason to teach it to bootcamp students. Most of the students are lost in simple stuff like props, state, and writing APIs. Should probably concentrate on advanced SQL, implementing streaming data, async/await, advanced testing, typescript, etc.
> 
> That you mention knex tells the story. Students are still relying on knex, they should go to raw sql before you start with more abstractions on top of it.

As seen in [this repository](https://github.com/gebhartn/save-graphql/blob/master/prisma/utils/schema.sql), Prisma 2 behaves more like a traditional ORM and leaves room for raw SQL to describe your database before introspection. 

Additionally, GraphQL and TypeScript are built with incremental adoption in mind, Subscriptions are a valid introduction to working with streams, and the nature of database design in the context of the aforementioned incremental adoption provides a good opportunity to see the evolution of an API as it grows in complexity, emphasizing the rationale behind type safety and code generation to begin with.

**Comment by Embiggenerd** [comment]
> > I don't think being a fan of a spec is a good reason to teach it to bootcamp students. Most of the students are lost in simple stuff like props, state, and writing APIs. Should probably concentrate on advanced SQL, implementing streaming data, async/await, advanced testing, typescript, etc.
> > That you mention knex tells the story. Students are still relying on knex, they should go to raw sql before you start with more abstractions on top of it.
> 
> As seen in [this repository](https://github.com/gebhartn/save-graphql/blob/master/prisma/utils/schema.sql), Prisma 2 behaves more like a traditional ORM and leaves room for raw SQL to describe your database before introspection.
> 
> Additionally, GraphQL and TypeScript are built with incremental adoption in mind, Subscriptions are a valid introduction to working with streams, and the nature of database design in the context of the aforementioned incremental adoption provides a good opportunity to see the evolution of an API as it grows in complexity, emphasizing the rationale behind type safety and code generation to begin with.

Clearly people have a bias to graphql, and are looking for excuses to use it without any real reason. For instance, the OP states the problem as prisma being too complex. The problem should sound something like 'without graphql, we can not accomplish these various tasks. Graphql allows us to accomplish these tasks because XYZ. These tasks are valuable because ABC.'

You are not only losing the opportunity to teach more valuable tools, you are teaching the students that your decision making regarding tech choices should prioritize hype.

No one here is doing a cost/benefit analysis, no one has mentioned how many milliseconds graphql adds to every request. Whatever the decision, I hope it has a better foundation than what I read in this thread.

**Comment by gebhartn** [comment]
> Clearly people have a bias to graphql, and are looking for excuses to use it without any real reason. For instance, the OP states the problem as prisma being too complex. The problem should sound something like 'without graphql, we can not accomplish these various tasks. Graphql allows us to accomplish these tasks because XYZ. These tasks are valuable because ABC.'
> 
> You are not only losing the opportunity to teach more valuable tools, you are teaching the students that your decision making regarding tech choices should prioritize hype.
> 
> No one here is doing a cost/benefit analysis, no one has mentioned how many milliseconds graphql adds to every request. Whatever the decision, I hope it has a better foundation than what I read in this thread.

While I agree that I'm here rallying for GraphQL because I enjoy working with it, the objective here isn't to enforce a rule to strictly teach GraphQL to students, but to preserve it as an optional engineering standard for students that are interested in using it for their Labs projects, perhaps as an opt-in.

I also agree that there are potentially some pitfalls to using an immature tool, and that there are trade-offs to be considered when making any decision, but nobody is advocating for GraphQL as a 1:1 replacement for RESTful APIs in Labs, just as an alternative technology for students who want to try something new.

**Comment by aapclark** [comment]
> No one here is doing a cost/benefit analysis, no one has mentioned how many milliseconds graphql adds to every request. Whatever the decision, I hope it has a better foundation than what I read in this thread.

For what it's worth, I don't think most labs teams get to a point where they're considering shaving off a few MS between API calls as their next most-valuable contribution.

The cost/benefit analysis should just be concerned with more performance, in my opinion. One of Lambda School's best contributions to students is teaching them _how_ to flourish while learning new concepts/working in unfamiliar territory. I think GraphQL and associated stacks are _just_ different enough that they have the opportunity to really push developers into different ways of thinking. That's a big benefit – not necessarily in the sense that they can look for jobs utilizing GQL, but that they can communicate their experience picking up a largely foreign tech stack and thriving and learning from the experience. 

I know that not everyone has that perspective on GraphQL, or, specifically, Prisma/devops hiccups. But I'm a much better developer for having worked through a GraphQL+Apollo+Prisma+Docker stack.

**Comment by JimmyMcBride** [comment]
> > > I don't think being a fan of a spec is a good reason to teach it to bootcamp students. Most of the students are lost in simple stuff like props, state, and writing APIs. Should probably concentrate on advanced SQL, implementing streaming data, async/await, advanced testing, typescript, etc.
> > > That you mention knex tells the story. Students are still relying on knex, they should go to raw sql before you start with more abstractions on top of it.
> > 
> > 
> > As seen in [this repository](https://github.com/gebhartn/save-graphql/blob/master/prisma/utils/schema.sql), Prisma 2 behaves more like a traditional ORM and leaves room for raw SQL to describe your database before introspection.
> > Additionally, GraphQL and TypeScript are built with incremental adoption in mind, Subscriptions are a valid introduction to working with streams, and the nature of database design in the context of the aforementioned incremental adoption provides a good opportunity to see the evolution of an API as it grows in complexity, emphasizing the rationale behind type safety and code generation to begin with.
> 
> Clearly people have a bias to graphql, and are looking for excuses to use it without any real reason. For instance, the OP states the problem as prisma being too complex. The problem should sound something like 'without graphql, we can not accomplish these various tasks. Graphql allows us to accomplish these tasks because XYZ. These tasks are valuable because ABC.'
> 
> You are not only losing the opportunity to teach more valuable tools, you are teaching the students that your decision making regarding tech choices should prioritize hype.
> 
> No one here is doing a cost/benefit analysis, no one has mentioned how many milliseconds graphql adds to every request. Whatever the decision, I hope it has a better foundation than what I read in this thread.

There are a ton of amazing benefits of using GraphQL over REST that are pretty common knowledge at this point. Some of the benefits of GraphQL include:

- A single, infinitely flexible endpoint instead of TONS of different endpoints. Makes requesting information from the database easier cause you don't have to think about what endpoint to hit, just what function you want to run and what you want to retrieve or change in that database.
- Great built-in type safety.
- Only retrieving the data you need and nothing more.
- It allows you to gain a deep understanding of how your data is being used through GraphQL's amazing resolver function system.

The list goes on. GraphQL is the future. Apollo comes baked with a subscription system using WebSockets under the hood to help you, very easily build a real-time database.

In addition, using the apollo client on the front end allows you to update your cache, which updates your UI everywhere. There is an easy built-in method for sending a new network request to update your cache or you can manually update your cache yourself saving you the extra network request. 

That feature alone blows Redux out of the water for me. I'm a big fan of Redux too, but Apollo client offers so much more. It's been such an amazing dev experience so far.

If all that doesn't get you hyped about GraphQL, then don't use it. :heart: To each their own, but I don't think microseconds worth of performance is that big of a deal to worry about.

**Comment by JimmyMcBride** [comment]
@gebhartn Said it the best. I'm not trying to change the curriculum, I just want future teams to have the choice to choose an amazing technology like GraphQL for their lab's project. Because I'm such a fan is my motivation for opening this issue and providing what I see as a solution to the problem and taking into account things students already learn through the lambda curriculum and building on top of that knowledge. Instead of learning a whole new stack and having to learn many things at the same time, give them just one thing to add to what they already know, if they so choose.

**Comment by Memitaru** [comment]
> @gebhartn Said it the best. I'm not trying to change the curriculum, I just want future teams to have the choice to choose an amazing technology like GraphQL for their lab's project. Because I'm such a fan is my motivation for opening this issue and providing what I see as a solution to the problem and taking into account things students already learn through the lambda curriculum and building on top of that knowledge. Instead of learning a whole new stack and having to learn many things at the same time, give them just one thing to add to what they already know, if they so choose.

Along with this I think it's for students the ability to research and justify their choices is a valuable experience. It makes sense to narrow the options in order to provide the best support, but I also know my groups benefited a lot from the work they put in to choosing to use GraphQL. 

If we want students to have some options where they can research and make decisions then it's important to consider the difficulty of introducing that new technology to make sure they can fit it into the eight weeks they get and still ship some great features. GraphQL fits that really well.

**Comment by nickdurbin** [comment]
@Embiggenerd 

This forum is requesting that it at the very least still be an option for students. NOT forcing them to learn a new technology for the sake of learning it. 

There are many ways to accomplish a task and some are better tools than others. For the most part, I do not think any of us are experienced enough to determine without a doubt that X is better than Y, but I would still enjoy having the OPTION to see if it is.

**Comment by JoeLorenzo** [comment]
Getting rid of GraphQL entirely from labs because Prisma has given some teams problems is throwing the baby out with the bath water.

**Comment by Embiggenerd** [comment]
I think a big part of the support for graphql is that you guys don't know what you're missing - typescript is close to industry standard, rigorous testing is industry standard. Logging, caching, monitoring and observability are all going to be present at whatever jobs you get. Not to mention service oriented architecture and how that complicates everything.

High level tools that take care of a bunch of problems at once, like the Apollo client, teach you how to configure Apollo client. I know it's cool, know there's hype, but "it's amazing" doesn't pass in a job interview for why you chose a particular tool.

Allowing graphql at the cost of a million more useful tools is a strange decision, and I know that leadership knows it's a strange decision. Doesn't mean it's the wrong one. At least have better arguments than 'it's amazing'. Anything anyone ever says is amazing never is lol

**Comment by michelangelo17** [comment]
@Embiggenerd I think the point is that they've consistently narrowed the stack, and while yes, it is good to focus on fundamentals, a huge part of what Labs focuses on is to make you do research and choose the tools you are going to use to solve the problem and to also familiarize yourself with an unfamiliar tool-set. (Such as what you'll surely be faced with at a new job.) 

Now, do I believe the curriculum should ditch Knex entirely and teach SQL straight up instead? Absolutely. Do I think testing is under-taught? Definitely. Do I think exposure to TypeScript would be invaluable? Of course. 

But we're not talking about the curriculum. We're talking about what options should be available for students to research and choose from and leaving out GraphQL as a potential API backend entirely seems excessive. 

On my project we chose to use a REST API (greenfield project), but we chose that AFTER researching the advantages and disadvantages of both, weighing the pros and cons as a group and determining for our use case it didn't offer a compelling advantage. 

So now I get to explain that decision to others when they ask about it and my answer is based on research and not on "Lambda told me it had to be REST."

**Comment by dave-vazquez** [comment]
> Now, do I believe the curriculum should ditch Knex entirely and teach SQL straight up instead? Absolutely.

**Off-topic**, but Amen to this brother. If a student can't write anything beyond a basic SQL query, they're lost if they're trying to write something more complex and having to find, learn and execute the correct chain of knex methods to get it working. So much time wasted if knex was ditched in favor of diving deeper into any one of the SQL languages. 

Same is true if they dedicated more time to database design which is an art in-and-of-itself. I don't think benefits of being able to easily switch between DBs with knex out-weigh the benefits of learning how to leverage the power that raw SQL provides. Then again, I also understand the challenges of designing a curriculum that covers all these fronts with the limited time boot-camp styled schools have available to them.

**On-topic**, GraphQL's power comes from exposing a single API end-point, and offering declarative data fetching which is great for rapid feature development in Labs. If your UI changes, you don't have to re-write end-points to support the data requirements of those changes the way that you have to with RESTful APIs. 

Awesome that you weighed the pros and cons of both though and you settled on REST as the best option for the needs of your specific product. That's what students in Labs should be doing anyways and why keeping GraphQL in the standards is far less about "hype" and more about green-lighting alternate specs that offer unique advantages that other specs don't.

**Comment by JimmyMcBride** [comment]
Before they teach knex, they taught raw SQL first. They didn't teach us how to build a whole back end using raw SQL, but they taught us fundamentals before teaching knex.

Lambda only has so much time to teach you. Lambda brushes the top of every important topic and it's up to each of us to dig deeper. Lambda is a stepping stone. They aren't responsible for teaching us everything we need to learn, that's not on them. It's up to us to dig deeper. 

There is SO much to learn when it comes to being a dev. The best quality you can have as a dev is the ability to learn something new.

I haven't even graduated and I know several different ORM's (Prisma 1, TypeORM, Delisle, sqlAlchemy). I know how to make local databases and write raw SQL scripts to do what I want it to do. I know TypeScript, I've multiple npm packages including my own style library, a discord bot, my own CRA templates, a todo cli you can install through npm. I'm currently learning how to write node packages in Rust. I'm not saying this to brag, I'm not as phenomenal of a student as @dave-vazquez or @michelangelo17. There are always going to be people more talented and intelligent than me. I thought I was pretty good with Linux until I met @gebhartn and he has actually shared some really valuable Linux/bash/vim wisdom with me that I really appreciate. 

My point is, Lambda didn't teach me a lot of those things I just listed. The classroom plays a very vital, but overall a small role in actual learning. Real learning is what happens outside the classroom. The classroom just does it's best to prepare you for the actual learning outside the class, outside the books, and that's all on the individual. 

Lambda has 9 (or 18) months to cover a HUGE array to topics, especially for full-stack development. From HTML and CSS all the way to Python, algo's, and graphs. We don't live in the matrix that can't just download how to be a programmer in our brain for us.

As far as the curriculum goes, I think Lambda really nails it personally. :rocket: :tada:

**Comment by berniedurfee** [comment]
Wow! 🤩 Thank you all for being so passionate and engaged! It's threads like these that make me _absolutely_ love being a part of Lambda School. 😁

We're certainly living in a golden age of software engineering. The rate at which software as a discipline, skill and art is accelerating and improving is staggering. New technologies around every corner, each built on learnings from the rich history of our industry.

Choosing from this continuously evolving array of tools and platforms is one of the great challenges of being a software architect. Many choices, almost all of them will get the job done, yet you must weigh _all_ the factors to make the best selections.

At some point, all organizations need to down-select from the grand menu of all technologies. The methodology used to select the core technologies used by an organization is _very_ specific to each business. It needs to factor in their product needs, budget, existing expertise and a host of other factors.

I won't go into all the details, though it'd be fun, but the decision to back away from GraphQL was made because it's the right decision for the overall success of Lambda School Labs a this moment in time. I _do not_ expect GraphQL to be outside of our tech stack for long. I don't think you need a crystal ball to see that GraphQL will be a core technology in the future. It just isn't right for us, right now.

Here are some of the basic factors that drove the decision:

1. Popularity - While the use of GraphQL is rapidly expanding, it isn't yet firmly in the mainstream. We can only permit so many technologies in Labs before we lose the ability to teach, support and assess students based on their work. It pains us to say it, because we love exploring new technologies, but popularity and market share will always be a driving factor when we need to choose between different technologies with the same purpose.

2. Maturity - The technology landscape around GraphQL is rapidly evolving. There are many tools, platforms and services struggling to gain a foothold and many efforts will fail as the technology stabilizes. This presents a significant problem for adoption by Labs, as our engineers (aka our students) come and go every couple months. Combining rapid turnover (conversely zero retention) with a rapidly changing technology can create havoc, as teams will be constantly inheriting obsolete technology. Therefor, we tend to err on the side of choosing more mature and stable technologies for our Labs tech stack.

3. Complexity - As technologies mature and become stable, the community supporting those technologies begins to optimize tooling for ease of adoption. The frameworks become easier to use, platforms provide easily hosted solutions and integration with other technologies expands rapidly. GraphQL is not yet in that place of stability, where you can be confident that a framework will have everything you need to go from design to production without duct tape and bailing wire. While there are many exciting frameworks like https://redwoodjs.com/ that are building end-to-end solutions, the market isn't quite there yet.

Hopefully this helps to explain why we're stepping back from GraphQL for the time being. It's simple not mature enough that we can support it in our organization.

These are really hard decisions and we invest many hours in discussing and weighing our options. It may not always be evident why the standards have been crafted the way they are, but you can be assured that they're optimized to deliver the best students experience that we think possible.

This particular decision is definitely a decision that we'll revisit periodically and I'm certain it'll be a part of our stack in the near future.

Thanks again for the discussion and for your passion!! 👍
